[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
# runner = "arm-none-eabi-gdb -q"
runner = "gdb-multiarch -q -x openocd.gdb"  
# runner = "gdb -q"
rustflags = [
  "-C", "link-arg=-Tlink.x",
]